multi_branch_env:
  hostname: tr.rt.gw
  user: root
  site_url: https://hilay-trivedi.tr.rt.gw
  main_site: hilay-trivedi.tr.rt.gw
  deploy_path: /opt/easyengine/sites/hilay-trivedi.tr.rt.gw/app/htdocs